import React from "react";
import { withBaseIcon } from "react-icons-kit";
import { ic_language } from "react-icons-kit/md/ic_language";
import { ic_view_list } from "react-icons-kit/md/ic_view_list";
import { book } from "react-icons-kit/icomoon/book";
import { ic_feedback } from "react-icons-kit/md/ic_feedback";
import { ic_search } from "react-icons-kit/md/ic_search";
import { ic_close } from "react-icons-kit/md/ic_close";
import { ic_send } from "react-icons-kit/md/ic_send";
import { ic_add_circle } from "react-icons-kit/md/ic_add_circle";
import { ic_check_circle } from "react-icons-kit/md/ic_check_circle";
import { thumbsOUp } from "react-icons-kit/fa/thumbsOUp";
import { thumbsUp } from "react-icons-kit/fa/thumbsUp";
import { ic_share } from "react-icons-kit/md/ic_share";
import { ic_lock_outline } from "react-icons-kit/md/ic_lock_outline";
import { ic_list } from "react-icons-kit/md/ic_list";

const IconContainer = withBaseIcon({ size: 24 });
export const IconLan = () => <IconContainer icon={ic_language} />;
export const IconViewList = () => <IconContainer icon={ic_view_list} />;
export const IconBook = () => <IconContainer icon={book} />;
export const IconFeedBack = () => <IconContainer icon={ic_feedback} />;
export const IconSearch = () => <IconContainer icon={ic_search} />;
export const IconClose = () => <IconContainer icon={ic_close} />;
export const IconSend = () => <IconContainer icon={ic_send} />;
export const IconAdd = () => <IconContainer icon={ic_add_circle} />;
export const IconCheckCircle = () => <IconContainer icon={ic_check_circle} />;
export const IconThumbUpOutline = () => <IconContainer icon={thumbsOUp} />;
export const IconThumbDown = () => <IconContainer icon={thumbsUp} />;
export const IconShare = () => <IconContainer icon={ic_share} />;
export const IconLock = () => <IconContainer icon={ic_lock_outline} />;
export const IconList = () => <IconContainer icon={ic_list} />;
